      - name: Download SDK
        run: |
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/archive/master.zip -o sdks.zip
          unzip sdks.zip
          mv sdks-master/* ~/theos/sdks/
          rm -rf sdks-master sdks.zip
